### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zeusro** [stlyx/DNSPodToMe#1]
https://github.com/stlyx/DNSPodToMe/blob/master/dns_to_me.go#L99
日志一般放 logs/yyyy-MM-dd 文件夹里面

https://github.com/stlyx/DNSPodToMe/blob/master/dns_to_me.go#L112
		time.Sleep(10 * time.Minute)
就行

https://github.com/stlyx/DNSPodToMe/blob/master/dns_to_me.go#L143
 json.Unmarshal(body1, &rl)
也行

https://github.com/stlyx/DNSPodToMe/blob/master/dns_to_me.go#L217
地址一般用ENV而不是常量表示

https://github.com/stlyx/DNSPodToMe/blob/master/dns_to_me.go#L233
缺乏配置的样例。这是一个配置文件，但是你的.gitignore 忽略了这个文件。

其他建议：
1. 结构体 struct  建议放在 types.go 里面
1. 输出日志建议制定一个通用的结构，方便聚合统计

**Comment by stlyx** [comment]
1. Not designed for log rotation, only one log will be generated. 
2. Okay... 
3. Explicitly ignore the io error according to GoLand suggestion. 
4. Will use another common and fixed API. 
5. Sensitive data removal.

**Comment by zeusro** [comment]
Well done.
